insert into users (firstName, lastName, email, password) values ('John', 'Smith', 'jsmith@email.com', 'password1');
insert into users (firstName, lastName, email, password) values ('Sarine', 'Alexsandrovich', 'salexsandrovich1@reddit.com', 'DdT9tH1uWyE');
insert into users (firstName, lastName, email, password) values ('Shari', 'Brind', 'sbrind2@google.es', 'HcdkrOyr4jIC');
insert into users (firstName, lastName, email, password) values ('Candice', 'Maplethorpe', 'cmaplethorpe3@reverbnation.com', 'gqJGBDglQEbl');
insert into users (firstName, lastName, email, password) values ('Chrisy', 'Cowern', 'ccowern4@oakley.com', 'Lwlvco1oeR');
insert into users (firstName, lastName, email, password) values ('Jess', 'Waywell', 'jwaywell5@hatena.ne.jp', 'fSmEIP6765');
insert into users (firstName, lastName, email, password) values ('Scarface', 'Hastie', 'shastie6@liveinternet.ru', 'maAdzO');
insert into users (firstName, lastName, email, password) values ('Ed', 'Mary', 'emary7@twitpic.com', 'GvgxuN');
insert into users (firstName, lastName, email, password) values ('Thacher', 'Stallon', 'tstallon8@yahoo.com', 'Cmd67WFP4hC7');
insert into users (firstName, lastName, email, password) values ('Wayne', 'Schiell', 'wschiell9@smh.com.au', 'F2EfkZ');
insert into users (firstName, lastName, email, password) values ('Ivette', 'Gildea', 'igildeaa@bing.com', 'PaBrCe0mtj5c');
insert into users (firstName, lastName, email, password) values ('Madelaine', 'Legge', 'mleggeb@youku.com', 'llUjjaSI3');
insert into users (firstName, lastName, email, password) values ('Thadeus', 'Priestley', 'tpriestleyc@youku.com', 'cZTFIF');
insert into users (firstName, lastName, email, password) values ('Tasha', 'Arnaudin', 'tarnaudind@smugmug.com', 'mdpdjB');
insert into users (firstName, lastName, email, password) values ('Eb', 'Charlo', 'echarloe@disqus.com', 'UrpTOwq3');
insert into users (firstName, lastName, email, password) values ('Mirna', 'Acome', 'macomef@qq.com', 'fK3BIMebywuP');
insert into users (firstName, lastName, email, password) values ('Meghan', 'Garden', 'mgardeng@biblegateway.com', 'zdcdpcXSpL');
insert into users (firstName, lastName, email, password) values ('Umeko', 'Chevis', 'uchevish@answers.com', 'sMMWFv1hbnEO');
insert into users (firstName, lastName, email, password) values ('Dmitri', 'Gusticke', 'dgustickei@meetup.com', 'GbsFRn6gyc');
insert into users (firstName, lastName, email, password) values ('Wainwright', 'Pifford', 'wpiffordj@techcrunch.com', 'sxm4C0');

insert into data_plans (costPerDevice, numberOfDevices, planDescription) values (34.99, 1, "Basic plan. 2GB of high speed data.");
insert into data_plans (costPerDevice, numberOfDevices, planDescription) values (49.99, 2, "Advanced plan. Unlimited talk, text, data for 2 lines.");
insert into data_plans (costPerDevice, numberOfDevices, planDescription) values (39.99, 4, "Family plan. Unlimited talk, text, data for 4 lines.");

insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('2431578544', 1, 2, 'iPhone XS', 'Green');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('6002671726', 2, 2, 'iPhone SE', 'Maroon');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('5484748035', 3, 2, 'iPhone XR', 'Orange');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9783660256', 4, 3, 'iPhone 12', 'Blue');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('8191857959', 5, 2, 'iPhone 12', 'Khaki');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('7286978839', 6, 1, 'iPhone XS', 'Yellow');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('2101268894', 7, 2, 'iPhone 11', 'Indigo');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('3849067610', 8, 2, 'iPhone 11 Pro', 'Puce');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('4842402250', 9, 3, 'Galaxy S21', 'Green');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('4276494017', 10, 1, 'iPhone 11 Pro', 'Aquamarine');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('4044768369', 11, 2, 'iPhone XR', 'Yellow');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('7268497582', 12, 1, 'Galaxy Note 20', 'Blue');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9282283607', 13, 2, 'iPhone SE', 'Teal');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('2054194956', 14, 2, 'iPhone 12 Pro Max', 'Green');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('1557332002', 15, 2, 'Galaxy S21', 'Turquoise');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('5867463015', 16, 1, 'iPhone SE', 'Purple');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9145549511', 17, 1, 'iPhone 11', 'Blue');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('4993718705', 18, 3, 'iPhone 12 Pro Max', 'Aquamarine');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('8224504246', 19, 3, 'Galaxy Note 20', 'Turquoise');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9744998200', 20, 3, 'iPhone 12 Pro Max', 'Red');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9234963359', 1, 3, 'iPhone 11 Pro', 'Blue');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('4797609168', 2, 2, 'iPhone 12', 'Khaki');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('8685218889', 3, 3, 'Galaxy Note 10', 'Violet');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('8342313491', 4, 2, 'iPhone 11', 'Puce');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9462951048', 5, 3, 'Galaxy Note 20', 'Blue');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('2439689642', 6, 1, 'iPhone 12', 'Purple');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('1178650885', 7, 2, 'iPhone 11 Pro', 'Maroon');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('5269557147', 8, 3, 'iPhone XR', 'Goldenrod');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('3764869279', 9, 2, 'iPhone 11', 'Goldenrod');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('6713188921', 10, 3, 'Galaxy S21', 'Khaki');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('2446323961', 11, 3, 'Galaxy S20', 'Puce');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('4753610646', 12, 2, 'Galaxy Note 10', 'Khaki');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('2766577715', 13, 2, 'iPhone 11', 'Red');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('5929711111', 14, 3, 'Galaxy Note 10', 'Crimson');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('4838609335', 15, 3, 'iPhone X', 'Green');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('7252962474', 16, 2, 'iPhone SE', 'Indigo');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('7277569827', 17, 1, 'iPhone XS', 'Goldenrod');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('6713574442', 18, 1, 'iPhone XR', 'Turquoise');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('2439599987', 19, 3, 'iPhone 11', 'Green');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('6757761955', 20, 3, 'iPhone X', 'Yellow');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('3162296055', 1, 2, 'iPhone 11', 'Teal');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('7187942798', 2, 1, 'iPhone XR', 'Mauv');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('8401630260', 3, 2, 'iPhone 12', 'Red');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('1874311731', 4, 2, 'iPhone X', 'Puce');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('6133777346', 5, 1, 'iPhone XS', 'Yellow');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('3102345944', 6, 2, 'iPhone SE', 'Khaki');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9084672895', 7, 3, 'iPhone X', 'Pink');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('1141756177', 8, 1, 'Galaxy Note 20', 'Purple');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('2185671511', 9, 2, 'iPhone 11', 'Red');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('5122851527', 10, 2, 'iPhone SE', 'Orange');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('2162077988', 11, 2, 'iPhone XR', 'Aquamarine');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9435543606', 12, 2, 'Galaxy Note 10', 'Indigo');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('7712018621', 13, 1, 'iPhone SE', 'Violet');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9479073510', 14, 3, 'iPhone 11 Pro', 'Aquamarine');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('5244798382', 15, 3, 'iPhone SE', 'Fuscia');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('2531661992', 16, 3, 'iPhone X', 'Indigo');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('1266856010', 17, 3, 'iPhone 11', 'Blue');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9621217842', 18, 2, 'Galaxy S20', 'Fuscia');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9437540437', 19, 3, 'Galaxy Note 20', 'Orange');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('6353820791', 20, 2, 'iPhone 11', 'Goldenrod');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9187986128', 1, 1, 'iPhone X', 'Khaki');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('4725797642', 2, 3, 'iPhone SE', 'Green');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('6874431994', 3, 1, 'iPhone XS', 'Crimson');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('4108745232', 4, 1, 'iPhone 12', 'Crimson');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('9668036954', 5, 1, 'Galaxy Note 10', 'Blue');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('6851861430', 6, 3, 'iPhone SE', 'Goldenrod');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('1593350042', 7, 2, 'iPhone X', 'Purple');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('5568320014', 8, 3, 'iPhone X', 'Purple');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('6217090578', 9, 3, 'Galaxy S20', 'Indigo');
insert into devices (phoneNumber, userID, dataPlanID, deviceName, deviceDescription) values ('3446341443', 10, 3, 'iPhone 12 Pro Max', 'Maroon');

